# Generated by Django 5.2.6 on 2025-09-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeContact',
        ),
    ]
