# Generated by Django 5.2.6 on 2025-09-29 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0002_remove_employee_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'. Maximum 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone'),
        ),
    ]
