# Generated by Django 5.2.6 on 2025-10-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0009_remove_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position_title',
            field=models.CharField(max_length=100, verbose_name='Titre du poste'),
        ),
    ]
