# Generated by Django 5.2.6 on 2025-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0015_remove_phone_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Désactivé si l'employé n'est plus dans LDAP", verbose_name='Actif'),
        ),
    ]
