# Generated by Django 5.2.6 on 2025-11-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0016_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
