# Generated by Django 5.2.6 on 2025-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_incident_date_sar', models.DateField(blank=True, help_text='Date du dernier accident SAR (interne)', null=True)),
                ('last_incident_date_ee', models.DateField(blank=True, help_text='Date du dernier accident EE (externe)', null=True)),
                ('last_incident_type_sar', models.CharField(blank=True, help_text='Type du dernier accident SAR', max_length=200, null=True)),
                ('last_incident_type_ee', models.CharField(blank=True, help_text='Type du dernier accident EE', max_length=200, null=True)),
                ('last_incident_description_sar', models.TextField(blank=True, help_text='Description du dernier accident SAR', null=True)),
                ('last_incident_description_ee', models.TextField(blank=True, help_text='Description du dernier accident EE', null=True)),
                ('safety_score', models.FloatField(default=100.0, help_text='Score de sécurité global (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Données de Sécurité',
                'verbose_name_plural': 'Données de Sécurité',
                'ordering': ['-updated_at'],
            },
        ),
    ]
