# Generated by Django 5.2.6 on 2025-09-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetydata',
            name='days_without_incident_ee',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de jours sans accident EE (externe)'),
        ),
        migrations.AddField(
            model_name='safetydata',
            name='days_without_incident_sar',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de jours sans accident SAR (interne)'),
        ),
        migrations.AlterField(
            model_name='safetydata',
            name='last_incident_date_ee',
            field=models.DateField(blank=True, help_text='Date du dernier accident EE (externe) - Calculée automatiquement', null=True),
        ),
        migrations.AlterField(
            model_name='safetydata',
            name='last_incident_date_sar',
            field=models.DateField(blank=True, help_text='Date du dernier accident SAR (interne) - Calculée automatiquement', null=True),
        ),
    ]
