# Generated by Django 5.2.6 on 2025-11-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code unique du département (ex: 'production', 'maintenance')", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Nom complet du département (ex: 'Production', 'Maintenance')", max_length=100)),
                ('emails', models.JSONField(blank=True, default=list, help_text="Liste des emails associés au département pour l'envoi groupé")),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le département est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='accueil_dep_code_eb2acc_idx'), models.Index(fields=['is_active'], name='accueil_dep_is_acti_32a12b_idx')],
            },
        ),
        migrations.AlterField(
            model_name='idea',
            name='department',
            field=models.ForeignKey(help_text="Département concerné par l'idée", on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='accueil.department'),
        ),
    ]
