# Generated by Django 5.2.6 on 2025-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_department_alter_idea_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nom du projet', max_length=200, null=True)),
                ('objective', models.TextField(blank=True, help_text='Objectif du projet', null=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du projet', null=True)),
                ('status', models.CharField(blank=True, choices=[('en_cours', 'Études en cours'), ('termine', 'Terminé'), ('planifie', 'Planifié'), ('en_projet', 'En projet')], help_text='Statut actuel du projet', max_length=20, null=True)),
                ('date_debut', models.DateField(blank=True, help_text='Date de début du projet', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin prévue du projet', null=True)),
                ('budget', models.CharField(blank=True, help_text="Budget du projet (ex: '3 000 Md FCFA')", max_length=100, null=True)),
                ('partners', models.TextField(blank=True, help_text='Partenaires du projet', null=True)),
                ('chef_projet', models.CharField(blank=True, help_text='Chef de projet', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image du projet', null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, help_text="URL de l'image du projet (pour les images externes)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le projet est actif')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = affiché en premier)")),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='accueil_pro_status_561374_idx'), models.Index(fields=['is_active'], name='accueil_pro_is_acti_fe110c_idx'), models.Index(fields=['order'], name='accueil_pro_order_4714df_idx')],
            },
        ),
    ]
