# Generated by Django 5.2.6 on 2025-09-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_safetydata_days_without_incident_ee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetydata',
            name='last_incident_date_ee',
        ),
        migrations.RemoveField(
            model_name='safetydata',
            name='last_incident_date_sar',
        ),
        migrations.RemoveField(
            model_name='safetydata',
            name='last_incident_description_ee',
        ),
        migrations.RemoveField(
            model_name='safetydata',
            name='last_incident_description_sar',
        ),
        migrations.RemoveField(
            model_name='safetydata',
            name='last_incident_type_ee',
        ),
        migrations.RemoveField(
            model_name='safetydata',
            name='last_incident_type_sar',
        ),
        migrations.RemoveField(
            model_name='safetydata',
            name='safety_score',
        ),
    ]
