# Generated by Django 5.2.6 on 2025-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0003_remove_safetydata_last_incident_date_ee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Description détaillée de l'idée")),
                ('department', models.CharField(choices=[('production', 'Production'), ('maintenance', 'Maintenance'), ('quality', 'Qualité'), ('safety', 'Sécurité'), ('logistics', 'Logistique'), ('it', 'Informatique'), ('hr', 'Ressources Humaines'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('other', 'Autre')], help_text="Département concerné par l'idée", max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('under_review', "En cours d'examen"), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('implemented', 'Implémentée')], default='submitted', help_text="Statut actuel de l'idée", max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Idée',
                'verbose_name_plural': 'Idées',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
