# Generated by Django 5.2.6 on 2025-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0003_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='accueil_pro_is_acti_fe110c_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='accueil_pro_order_4714df_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.AddField(
            model_name='project',
            name='titre',
            field=models.CharField(blank=True, help_text='Titre du projet', max_length=200, null=True),
        ),
    ]
