# Generated by Django 5.2.6 on 2025-09-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_idea'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du plat', max_length=200)),
                ('type', models.CharField(choices=[('senegalese', 'Sénégalais'), ('european', 'Européen')], help_text='Type de cuisine', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description du plat', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Disponibilité du plat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DayMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], help_text='Jour de la semaine', max_length=20)),
                ('date', models.DateField(help_text='Date du menu')),
                ('is_active', models.BooleanField(default=True, help_text='Menu actif ou non')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('european', models.ForeignKey(help_text='Plat européen du jour', limit_choices_to={'type': 'european'}, on_delete=django.db.models.deletion.CASCADE, related_name='european_menus', to='accueil.menuitem')),
                ('senegalese', models.ForeignKey(help_text='Plat sénégalais du jour', limit_choices_to={'type': 'senegalese'}, on_delete=django.db.models.deletion.CASCADE, related_name='senegalese_menus', to='accueil.menuitem')),
            ],
            options={
                'verbose_name': 'Menu du Jour',
                'verbose_name_plural': 'Menus des Jours',
                'ordering': ['date', 'day'],
                'unique_together': {('day', 'date')},
            },
        ),
    ]
