# Generated by Django 5.2.6 on 2025-11-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymenu',
            name='day',
            field=models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], help_text='Jour de la semaine', max_length=20),
        ),
    ]
