# Generated by Django 5.2.6 on 2025-11-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_remove_friday_from_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymenu',
            name='dessert',
            field=models.ForeignKey(blank=True, help_text='Dessert du jour', limit_choices_to={'type': 'dessert'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dessert_menus', to='accueil.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('senegalese', 'Sénégalais'), ('european', 'Européen'), ('dessert', 'Dessert')], help_text='Type de cuisine', max_length=20),
        ),
    ]
