# Generated by Django 5.2.6 on 2025-09-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_menuitem_daymenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre court et descriptif de l'événement", max_length=200, verbose_name="Titre de l'événement")),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'événement", verbose_name='Description')),
                ('date', models.DateField(help_text="Date de l'événement", verbose_name='Date')),
                ('time', models.TimeField(blank=True, help_text="Heure de début de l'événement", null=True, verbose_name='Heure')),
                ('location', models.CharField(help_text="Lieu où se déroule l'événement", max_length=200, verbose_name='Lieu')),
                ('type', models.CharField(choices=[('meeting', 'Réunion'), ('training', 'Formation'), ('celebration', 'Célébration'), ('conference', 'Conférence'), ('other', 'Autre')], default='other', help_text="Catégorie de l'événement", max_length=20, verbose_name="Type d'événement")),
                ('attendees', models.PositiveIntegerField(default=0, help_text='Nombre estimé de participants', verbose_name='Nombre de participants')),
                ('is_all_day', models.BooleanField(default=False, help_text="Cochez si l'événement dure toute la journée", verbose_name='Toute la journée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['date'], name='accueil_eve_date_5f4c67_idx'), models.Index(fields=['type'], name='accueil_eve_type_e9bb70_idx'), models.Index(fields=['is_all_day'], name='accueil_eve_is_all__3b398f_idx')],
            },
        ),
    ]
