# Generated by Django 5.2.6 on 2025-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0006_add_dessert_to_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymenu',
            name='dessert',
            field=models.CharField(blank=True, help_text='Nom du dessert du jour', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='european',
            field=models.CharField(blank=True, help_text='Nom du plat européen du jour', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='senegalese',
            field=models.CharField(blank=True, help_text='Nom du plat sénégalais du jour', max_length=200, null=True),
        ),
    ]
