# Generated by Django 5.2.6 on 2025-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0007_questionnaire_question_questionnaireresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='checkbox_text',
            field=models.TextField(blank=True, default="J'accepte les conditions", help_text='Texte affiché à côté de la case obligatoire', verbose_name='Texte de la case'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_labels',
            field=models.JSONField(blank=True, default=list, help_text='Labels personnalisés pour les étoiles et notes', verbose_name='Labels de notation'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_max',
            field=models.IntegerField(default=5, help_text='Note maximum pour les étoiles et notes numériques', verbose_name='Note maximum'),
        ),
        migrations.AddField(
            model_name='question',
            name='satisfaction_options',
            field=models.JSONField(blank=True, default=list, help_text="Options pour l'échelle de satisfaction", verbose_name='Options de satisfaction'),
        ),
        migrations.AddField(
            model_name='question',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Règles de validation spécifiques (email, téléphone, etc.)', verbose_name='Règles de validation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Texte libre'), ('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('scale', 'Échelle'), ('date', 'Date'), ('file', 'Fichier'), ('rating', 'Note'), ('rating_stars', 'Étoiles'), ('rating_numeric', 'Note sur 10'), ('satisfaction_scale', 'Échelle de satisfaction'), ('email', 'Email'), ('phone', 'Téléphone'), ('required_checkbox', 'Case obligatoire'), ('date_range', 'Plage de dates')], default='single_choice', help_text='Type de question', max_length=20, verbose_name='Type'),
        ),
    ]
