# Generated by Django 5.2.6 on 2025-09-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0008_question_checkbox_text_question_rating_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likert_scale',
            field=models.JSONField(blank=True, default=list, help_text="Options de l'échelle de Likert", verbose_name='Échelle de Likert'),
        ),
        migrations.AddField(
            model_name='question',
            name='matrix_options',
            field=models.JSONField(blank=True, default=list, help_text='Liste des options communes pour toutes les questions', verbose_name='Options de la matrice'),
        ),
        migrations.AddField(
            model_name='question',
            name='matrix_questions',
            field=models.JSONField(blank=True, default=list, help_text='Liste des questions pour la matrice', verbose_name='Questions de la matrice'),
        ),
        migrations.AddField(
            model_name='question',
            name='ranking_items',
            field=models.JSONField(blank=True, default=list, help_text='Liste des éléments à classer par ordre de priorité', verbose_name='Éléments à classer'),
        ),
        migrations.AddField(
            model_name='question',
            name='top_selection_limit',
            field=models.IntegerField(default=3, help_text="Nombre maximum d'éléments à sélectionner", verbose_name='Limite de sélection'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Texte libre'), ('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('scale', 'Échelle'), ('date', 'Date'), ('file', 'Fichier'), ('rating', 'Note'), ('rating_stars', 'Étoiles'), ('rating_numeric', 'Note sur 10'), ('satisfaction_scale', 'Échelle de satisfaction'), ('email', 'Email'), ('phone', 'Téléphone'), ('required_checkbox', 'Case obligatoire'), ('date_range', 'Plage de dates'), ('ranking', 'Classement'), ('top_selection', 'Top 3'), ('matrix', 'Matrice de choix'), ('likert', 'Échelle de Likert')], default='single_choice', help_text='Type de question', max_length=20, verbose_name='Type'),
        ),
    ]
