# Generated by Django 5.2.6 on 2025-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0009_question_likert_scale_question_matrix_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetydata',
            name='days_without_incident_ee',
        ),
        migrations.RemoveField(
            model_name='safetydata',
            name='days_without_incident_sar',
        ),
        migrations.AddField(
            model_name='safetydata',
            name='last_incident_date_ee',
            field=models.DateTimeField(blank=True, help_text='Date du dernier accident EE (externe)', null=True),
        ),
        migrations.AddField(
            model_name='safetydata',
            name='last_incident_date_sar',
            field=models.DateTimeField(blank=True, help_text='Date du dernier accident SAR (interne)', null=True),
        ),
        migrations.AddField(
            model_name='safetydata',
            name='last_incident_description_ee',
            field=models.TextField(blank=True, help_text='Description du dernier accident EE'),
        ),
        migrations.AddField(
            model_name='safetydata',
            name='last_incident_description_sar',
            field=models.TextField(blank=True, help_text='Description du dernier accident SAR'),
        ),
        migrations.AddField(
            model_name='safetydata',
            name='last_incident_type_ee',
            field=models.CharField(blank=True, help_text='Type du dernier accident EE', max_length=100),
        ),
        migrations.AddField(
            model_name='safetydata',
            name='last_incident_type_sar',
            field=models.CharField(blank=True, help_text='Type du dernier accident SAR', max_length=100),
        ),
        migrations.AddField(
            model_name='safetydata',
            name='safety_score',
            field=models.PositiveIntegerField(default=0, help_text='Score de sécurité global (0-100)'),
        ),
    ]
