# Generated by Django 5.2.6 on 2025-10-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom complet de la direction (ex: 'Ressources Humaines')", max_length=200, verbose_name='Nom de la direction')),
                ('slug', models.SlugField(help_text="Identifiant unique en minuscules pour les filtres (ex: 'rh')", max_length=200, unique=True, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('job_title', models.CharField(help_text="Poste ou fonction de l'agent", max_length=200, verbose_name='Poste')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_fixed', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone fixe')),
                ('phone_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone mobile')),
                ('employee_id', models.CharField(help_text="Matricule unique de l'agent", max_length=50, unique=True, verbose_name='Matricule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text="Manager de l'agent (le DG n'a pas de manager)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='organigramme.agent', verbose_name='Manager')),
                ('directions', models.ManyToManyField(help_text="Directions auxquelles appartient l'agent", related_name='agents', to='organigramme.direction', verbose_name='Directions')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
