# Generated by Django 5.2.6 on 2025-10-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='avatar',
            field=models.URLField(blank=True, help_text="URL de l'avatar", null=True, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='agent',
            name='department_name',
            field=models.CharField(blank=True, help_text='Nom du département principal', max_length=200, null=True, verbose_name='Nom du département'),
        ),
        migrations.AddField(
            model_name='agent',
            name='hierarchy_level',
            field=models.IntegerField(default=1, verbose_name='Niveau hiérarchique'),
        ),
        migrations.AddField(
            model_name='agent',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Est manager'),
        ),
        migrations.AddField(
            model_name='agent',
            name='matricule',
            field=models.CharField(blank=True, help_text='Alias du matricule', max_length=50, null=True, verbose_name='Matricule (alias)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='office_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localisation du bureau'),
        ),
        migrations.AddField(
            model_name='agent',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone bureau'),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, help_text='Téléphone mobile principal', max_length=20, null=True, verbose_name='Téléphone mobile'),
        ),
        migrations.AddField(
            model_name='agent',
            name='position',
            field=models.IntegerField(default=0, verbose_name='ID de position'),
        ),
        migrations.AddField(
            model_name='agent',
            name='position_title',
            field=models.CharField(default='', help_text='Titre officiel du poste', max_length=200, verbose_name='Titre du poste'),
        ),
        migrations.AddField(
            model_name='agent',
            name='work_schedule',
            field=models.CharField(default='9h-17h', max_length=100, verbose_name='Horaire de travail'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone mobile (alias)'),
        ),
    ]
