# Generated by Django 5.2.6 on 2025-10-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0002_agent_avatar_agent_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='office_phone',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='phone',
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_fixed',
            field=models.CharField(blank=True, help_text='Numéro de téléphone fixe (optionnel)', max_length=20, null=True, verbose_name='Téléphone fixe'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_mobile',
            field=models.CharField(blank=True, help_text='Numéro de téléphone mobile (optionnel)', max_length=20, null=True, verbose_name='Téléphone mobile'),
        ),
    ]
