# Generated by Django 5.2.6 on 2025-10-14 10:25

import organigramme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0003_remove_redundant_phone_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'agent", null=True, upload_to=organigramme.models.avatar_upload_path, verbose_name='Avatar'),
        ),
    ]
