# Generated by Django 5.2.6 on 2025-10-14 10:34

from django.db import migrations


def migrate_matricule_data(apps, schema_editor):
    """Migrer les données de employee_id vers matricule"""
    Agent = apps.get_model('organigramme', 'Agent')
    
    for agent in Agent.objects.all():
        if agent.employee_id and not agent.matricule:
            agent.matricule = agent.employee_id
            agent.save()


def reverse_migrate_matricule_data(apps, schema_editor):
    """Migration inverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0004_change_avatar_to_imagefield'),
    ]

    operations = [
        migrations.RunPython(migrate_matricule_data, reverse_migrate_matricule_data),
    ]
