# Generated by Django 5.2.6 on 2025-10-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0005_remove_unused_fields_step1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(max_length=50, unique=True, verbose_name='Matricule', help_text='Matricule unique de l\'agent'),
        ),
        migrations.RemoveField(
            model_name='agent',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='work_schedule',
        ),
    ]
