# Generated by Django 5.2.6 on 2025-10-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0006_fix_matricule_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='position_title',
        ),
    ]
