# Generated by Django 5.2.6 on 2025-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0007_remove_position_title_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='slug',
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(help_text="Nom complet de la direction (ex: 'Ressources Humaines')", max_length=200, unique=True, verbose_name='Nom de la direction'),
        ),
    ]
