# Generated by Django 5.2.6 on 2025-10-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0008_remove_direction_slug_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_manager',
        ),
    ]
