# Generated by Django 5.2.6 on 2025-10-16 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0009_remove_is_manager_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='department_name',
        ),
        migrations.AddField(
            model_name='agent',
            name='main_direction',
            field=models.ForeignKey(blank=True, help_text="Direction principale de l'agent", null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigramme.direction', verbose_name='Direction principale'),
        ),
    ]
