# Generated by Django 5.2.6 on 2025-10-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0010_replace_department_name_with_main_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='position',
        ),
    ]
