# Generated by Django 5.2.6 on 2025-10-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0011_remove_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_active',
        ),
    ]
