# Generated by Django 5.2.6 on 2025-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramme', '0012_remove_is_active_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, help_text="Email de l'agent (peut être vide si non renseigné dans LDAP)", max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
