# Generated by Django 5.2.6 on 2025-11-06 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre de la conversation', max_length=300, verbose_name='Titre')),
                ('description', models.TextField(help_text='Contenu détaillé de la conversation', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Image associée à la conversation', null=True, upload_to='conversations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Image')),
                ('is_resolved', models.BooleanField(default=False, help_text='Indique si la conversation est résolue (pour les forums de support)', verbose_name='Résolu')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Nombre de fois que la conversation a été consultée', verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Utilisateur ayant créé cette conversation', on_delete=django.db.models.deletion.CASCADE, related_name='forum_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenu du commentaire', verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Utilisateur ayant créé ce commentaire', on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('conversation', models.ForeignKey(help_text='Conversation à laquelle appartient ce commentaire', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie de forum', max_length=200, verbose_name='Nom du forum')),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie de forum', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Image représentative du forum', null=True, upload_to='forums/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le forum est actif et visible', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='forum_forum_is_acti_902a7c_idx'), models.Index(fields=['created_at'], name='forum_forum_created_503bbe_idx')],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='forum',
            field=models.ForeignKey(help_text='Forum auquel appartient cette conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='forum.forum', verbose_name='Forum'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(help_text='Commentaire liké', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.comment', verbose_name='Commentaire')),
                ('user', models.ForeignKey(help_text='Utilisateur ayant liké le commentaire', on_delete=django.db.models.deletion.CASCADE, related_name='forum_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Like de commentaire',
                'verbose_name_plural': 'Likes de commentaires',
                'indexes': [models.Index(fields=['comment'], name='forum_comme_comment_b2c26b_idx'), models.Index(fields=['user'], name='forum_comme_user_id_56961f_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['conversation', 'created_at'], name='forum_comme_convers_a82a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='forum_comme_author__719dda_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='forum_comme_created_7f9d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['forum', '-created_at'], name='forum_conve_forum_i_392718_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['author'], name='forum_conve_author__96c1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_resolved'], name='forum_conve_is_reso_af3a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-created_at'], name='forum_conve_created_2e6192_idx'),
        ),
    ]
