# Generated by Django 5.2.6 on 2025-12-01 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du forum', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description du forum', null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('general', 'Général'), ('technique', 'Technique'), ('rh', 'Ressources Humaines'), ('projet', 'Projets'), ('autre', 'Autre')], default='general', help_text='Catégorie du forum', max_length=50, verbose_name='Catégorie')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le forum est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(help_text='Utilisateur qui a créé le forum', on_delete=django.db.models.deletion.CASCADE, related_name='created_forums', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenu du message', verbose_name='Contenu')),
                ('is_edited', models.BooleanField(default=False, help_text='Indique si le message a été modifié', verbose_name='Modifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('author', models.ForeignKey(help_text='Auteur du message', on_delete=django.db.models.deletion.CASCADE, related_name='forum_messages', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('forum', models.ForeignKey(help_text='Forum auquel appartient ce message', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.forum', verbose_name='Forum')),
            ],
            options={
                'verbose_name': 'Message de forum',
                'verbose_name_plural': 'Messages de forum',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['-created_at'], name='forum_forum_created_ecb455_idx'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['category'], name='forum_forum_categor_b957cb_idx'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['is_active'], name='forum_forum_is_acti_902a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='forummessage',
            index=models.Index(fields=['forum', '-created_at'], name='forum_forum_forum_i_52552e_idx'),
        ),
        migrations.AddIndex(
            model_name='forummessage',
            index=models.Index(fields=['author'], name='forum_forum_author__f55a0b_idx'),
        ),
    ]
