# Generated by Django 5.2.6 on 2025-11-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='content',
            field=models.TextField(blank=True, help_text='Contenu de la conversation (utilisé pour créer rapidement)', null=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True, help_text='Contenu détaillé de la conversation', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, help_text='Titre de la conversation', max_length=300, null=True, verbose_name='Titre'),
        ),
    ]
