# Generated by Django 5.2.6 on 2025-12-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forum',
            name='forum_forum_categor_b957cb_idx',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='category',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='description',
        ),
    ]
