# Generated by Django 5.2.6 on 2025-12-01 16:05

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_forum_forum_categor_b957cb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.ImageField(blank=True, help_text="Image d'identité du forum affichée en haut", null=True, upload_to=forum.models.forum_image_upload_path, verbose_name='Image du forum'),
        ),
    ]
