# Generated by Django 5.2.6 on 2025-11-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_conversation_content_alter_conversation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='image',
        ),
    ]
