# Generated by Django 5.2.6 on 2025-11-07 20:53

from django.db import migrations, models


def copy_description_to_message(apps, schema_editor):
    """Copie les données de description vers message avant suppression"""
    Conversation = apps.get_model('forum', 'Conversation')
    db_alias = schema_editor.connection.alias
    
    # Vérifier quelles colonnes existent
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='forum_conversation' 
            AND column_name IN ('message', 'description', 'title')
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}
    
    # Copier les données seulement si description existe
    if 'description' in existing_columns:
        for conversation in Conversation.objects.using(db_alias).all():
            # Copier description dans message si message est vide
            if hasattr(conversation, 'description') and conversation.description:
                if 'message' not in existing_columns or not conversation.message:
                    conversation.message = conversation.description
                    conversation.save(using=db_alias)
            # Sinon, utiliser content si message et description sont vides
            elif hasattr(conversation, 'content') and conversation.content:
                if 'message' not in existing_columns or not conversation.message:
                    conversation.message = conversation.content
                    conversation.save(using=db_alias)


def reverse_copy_description_to_message(apps, schema_editor):
    """Opération inverse : copier message vers description"""
    # Pas d'opération inverse nécessaire
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_conversation_image'),
    ]

    operations = [
        # Ajouter le champ message (si n'existe pas déjà)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Vérifier et ajouter message si nécessaire
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name='forum_conversation' AND column_name='message'
                            ) THEN
                                ALTER TABLE forum_conversation ADD COLUMN message TEXT;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="ALTER TABLE forum_conversation DROP COLUMN IF EXISTS message;"
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='conversation',
                    name='message',
                    field=models.TextField(blank=True, help_text='Message de la conversation', null=True, verbose_name='Message'),
                ),
            ]
        ),
        # Copier les données de description vers message
        migrations.RunPython(copy_description_to_message, reverse_copy_description_to_message),
        # Supprimer description et title (seulement si elles existent)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name='forum_conversation' AND column_name='description'
                            ) THEN
                                ALTER TABLE forum_conversation DROP COLUMN description;
                            END IF;
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name='forum_conversation' AND column_name='title'
                            ) THEN
                                ALTER TABLE forum_conversation DROP COLUMN title;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name='forum_conversation' AND column_name='description'
                            ) THEN
                                ALTER TABLE forum_conversation ADD COLUMN description TEXT;
                            END IF;
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name='forum_conversation' AND column_name='title'
                            ) THEN
                                ALTER TABLE forum_conversation ADD COLUMN title VARCHAR(300);
                            END IF;
                        END $$;
                    """
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='conversation',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='conversation',
                    name='title',
                ),
            ]
        ),
        migrations.AlterField(
            model_name='conversation',
            name='content',
            field=models.TextField(blank=True, help_text='Contenu de la conversation (utilisé pour créer rapidement, sera copié dans message)', null=True, verbose_name='Contenu'),
        ),
    ]
