# Generated by Django 5.2.6 on 2025-12-15 11:19

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image attachée au message', null=True, upload_to=forum.models.forum_message_image_upload_path, verbose_name='Image du message'),
        ),
    ]
