# Generated by Django 5.2.6 on 2025-11-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_description_to_message_remove_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='forum_conve_is_reso_af3a4f_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_resolved',
        ),
    ]
