# Generated by Django 5.2.6 on 2025-12-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forummessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummessage',
            name='content',
            field=models.TextField(blank=True, help_text='Contenu du message', verbose_name='Contenu'),
        ),
    ]
