# Generated by Django 5.2.6 on 2025-09-30 13:51

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nom du document', max_length=255, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du document', null=True, verbose_name='Description')),
                ('file', models.FileField(help_text='Fichier PDF à uploader', upload_to=documents.models.document_upload_path, verbose_name='Fichier PDF')),
                ('file_size', models.PositiveIntegerField(help_text='Taille du fichier en octets', verbose_name='Taille du fichier (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Compteur de téléchargements', verbose_name='Nombre de téléchargements')),
                ('is_active', models.BooleanField(default=True, help_text='Document actif (visible par tous)', verbose_name='Actif')),
                ('uploaded_by', models.ForeignKey(help_text='Utilisateur qui a uploadé le document', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'), models.Index(fields=['uploaded_by'], name='documents_d_uploade_6455fb_idx'), models.Index(fields=['is_active'], name='documents_d_is_acti_e5a870_idx')],
            },
        ),
    ]
