# Generated by Django 5.2.6 on 2025-09-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du service ou de la catégorie', max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie', null=True, verbose_name='Description')),
                ('color', models.CharField(default='#3B82F6', help_text="Couleur hexadécimale pour l'affichage", max_length=7, verbose_name='Couleur')),
                ('icon', models.CharField(default='file', help_text="Nom de l'icône (Lucide React)", max_length=50, verbose_name='Icône')),
                ('is_active', models.BooleanField(default=True, help_text='Catégorie active', verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage", verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Service ou catégorie du document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory', verbose_name='Catégorie'),
        ),
    ]
