# Generated by Django 5.2.6 on 2025-10-01 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcategory_document_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du dossier', max_length=255, verbose_name='Nom du dossier')),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du dossier', null=True, verbose_name='Description')),
                ('color', models.CharField(default='#6B7280', help_text="Couleur hexadécimale pour l'affichage", max_length=7, verbose_name='Couleur')),
                ('icon', models.CharField(default='folder', help_text="Nom de l'icône (Lucide React)", max_length=50, verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Dossier actif (visible par tous)', verbose_name='Actif')),
                ('created_by', models.ForeignKey(help_text='Utilisateur qui a créé le dossier', on_delete=django.db.models.deletion.CASCADE, related_name='created_folders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('parent', models.ForeignKey(blank=True, help_text='Dossier parent (null pour la racine)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder', verbose_name='Dossier parent')),
            ],
            options={
                'verbose_name': 'Dossier de documents',
                'verbose_name_plural': 'Dossiers de documents',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Dossier contenant le document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder', verbose_name='Dossier'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['parent'], name='documents_d_parent__408df5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['created_by'], name='documents_d_created_78ea1c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['is_active'], name='documents_d_is_acti_2fb2e2_idx'),
        ),
    ]
