# Generated by Django 5.2.6 on 2025-10-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricule',
            field=models.CharField(blank=True, help_text="Matricule unique de l'utilisateur", max_length=50, null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
