# Generated by Django 5.2.6 on 2025-10-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_fixed',
            field=models.CharField(blank=True, help_text='Numéro de téléphone fixe (bureau)', max_length=50, null=True, verbose_name='Téléphone fixe'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone personnel', max_length=50, null=True, verbose_name='Téléphone personnel'),
        ),
    ]
