# Generated by Django 5.2.6 on 2025-09-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='avatars/'),
        ),
    ]
