# Generated by Django 5.2.6 on 2025-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Numéro de téléphone de l'utilisateur", max_length=20, null=True),
        ),
    ]
