# Generated by Django 5.2.6 on 2025-10-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0015_remove_phone_constraints'),
        ('authentication', '0003_user_phone_fixed_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Département de l'utilisateur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='annuaire.department', verbose_name='Département'),
        ),
    ]
