# Generated by Django 5.2.6 on 2025-09-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text="Poste occupé par l'utilisateur dans l'entreprise", max_length=100, null=True),
        ),
    ]
