# Generated by Django 5.2.6 on 2025-10-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='avatars/users/', verbose_name='Photo de profil'),
        ),
    ]
