# Generated by Django 5.2.6 on 2025-09-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text="Département de l'utilisateur dans l'entreprise", max_length=100, null=True),
        ),
    ]
