# Generated by Django 5.2.6 on 2025-10-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text="Poste occupé par l'utilisateur (ex: DG, DSI, Comptable, Développeur)", max_length=100, null=True, verbose_name='Poste occupé'),
        ),
    ]
