# Generated by Django 5.2.6 on 2025-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricule',
            field=models.CharField(blank=True, help_text="Matricule unique de l'utilisateur dans l'entreprise", max_length=50, null=True, unique=True),
        ),
    ]
