# Generated by Django 5.2.6 on 2025-12-16 09:04

from django.db import migrations
from django.conf import settings


def force_staff_superuser_all_users(apps, schema_editor):
    """
    Migration de données : Force is_active=True, is_staff=True et is_superuser=True pour tous les utilisateurs
    """
    # Utiliser apps.get_model pour obtenir le modèle User dans le contexte de migration
    User = apps.get_model('authentication', 'User')
    
    # Mettre à jour tous les utilisateurs inactifs
    updated_active_count = User.objects.filter(
        is_active=False
    ).update(is_active=True)
    
    # Mettre à jour tous les utilisateurs qui n'ont pas déjà ces statuts
    updated_count = User.objects.filter(
        is_staff=False
    ).update(is_staff=True)
    
    updated_superuser_count = User.objects.filter(
        is_superuser=False
    ).update(is_superuser=True)
    
    print(f"✅ {updated_active_count} utilisateur(s) mis à jour avec is_active=True")
    print(f"✅ {updated_count} utilisateur(s) mis à jour avec is_staff=True")
    print(f"✅ {updated_superuser_count} utilisateur(s) mis à jour avec is_superuser=True")


def reverse_force_staff_superuser(apps, schema_editor):
    """
    Migration inverse : Ne fait rien car on ne peut pas vraiment inverser cette opération
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_position'),
    ]

    operations = [
        migrations.RunPython(
            force_staff_superuser_all_users,
            reverse_force_staff_superuser,
        ),
    ]
