# Generated by Django 5.2.6 on 2025-12-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_force_staff_superuser_all_users'),
    ]

    operations = [
    ]
