# Generated by Django 5.2.6 on 2025-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_phone',
            field=models.CharField(blank=True, help_text="Numéro de téléphone fixe du bureau de l'utilisateur", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Numéro de téléphone personnel de l'utilisateur", max_length=20, null=True),
        ),
    ]
