# Generated by Django 5.2.6 on 2025-09-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_add_office_phone_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, help_text="Token d'accès Google (chiffré)", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_avatar_url',
            field=models.URLField(blank=True, help_text="URL de l'avatar Google de l'utilisateur", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, help_text="Email Google de l'utilisateur", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text="ID Google unique de l'utilisateur", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.TextField(blank=True, help_text='Token de rafraîchissement Google (chiffré)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token_expires_at',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration du token Google", null=True),
        ),
    ]
