# Generated by Django 5.2.6 on 2025-12-16 11:01

import django.db.models.deletion
import security.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nom du document (ex: Règlement Intérieur, Guide de Sécurité)', max_length=255, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, help_text='Description du document affichée sur la carte', null=True, verbose_name='Description')),
                ('file', models.FileField(help_text='Fichier PDF à uploader', upload_to=security.models.security_document_upload_path, verbose_name='Fichier PDF')),
                ('icon', models.CharField(default='file-text', help_text="Nom de l'icône Lucide React (ex: file-text, shield, book-open, file-check)", max_length=50, verbose_name='Icône')),
                ('file_size', models.PositiveIntegerField(help_text='Taille du fichier en octets', verbose_name='Taille du fichier (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage des cartes (0 = premier)", verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Document actif (visible sur la page)', verbose_name='Actif')),
                ('uploaded_by', models.ForeignKey(help_text='Utilisateur qui a uploadé le document', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_security_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document de sécurité',
                'verbose_name_plural': 'Documents de sécurité',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='security_se_created_635ec0_idx'), models.Index(fields=['uploaded_by'], name='security_se_uploade_1320df_idx'), models.Index(fields=['is_active'], name='security_se_is_acti_52a770_idx'), models.Index(fields=['order'], name='security_se_order_f602c2_idx')],
            },
        ),
    ]
