# Generated by Django 5.2.6 on 2025-12-16 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a uploadé le document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_security_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par'),
        ),
    ]
