# Generated by Django 5.2.6 on 2025-12-22 10:09

import security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_securitydocument_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydocument',
            name='file',
            field=models.FileField(help_text='Fichier PDF ou image (JPG, PNG, GIF, WEBP) à uploader', upload_to=security.models.security_document_upload_path, verbose_name='Fichier'),
        ),
    ]
