# Generated by Django 5.2.6 on 2026-01-16 10:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('daily_active_users', 'Utilisateurs actifs quotidiens'), ('weekly_active_users', 'Utilisateurs actifs hebdomadaires'), ('monthly_active_users', 'Utilisateurs actifs mensuels'), ('total_users', 'Total utilisateurs'), ('total_articles', 'Total articles'), ('total_documents', 'Total documents'), ('total_forum_posts', 'Total messages forum')], max_length=50, verbose_name='Type de métrique')),
                ('value', models.IntegerField(default=0, verbose_name='Valeur')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Métrique application',
                'verbose_name_plural': 'Métriques application',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['metric_type', '-date'], name='metriques_a_metric__b5ade1_idx')],
                'unique_together': {('metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure de connexion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de déconnexion')),
                ('session_duration', models.DurationField(blank=True, null=True, verbose_name='Durée de session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Connexion utilisateur',
                'verbose_name_plural': 'Connexions utilisateurs',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['-login_time'], name='metriques_u_login_t_cce418_idx'), models.Index(fields=['user', '-login_time'], name='metriques_u_user_id_397ff7_idx')],
            },
        ),
    ]
