# Generated by Django 5.2.6 on 2025-09-07 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('news', 'Actualité'), ('poll', 'Sondage'), ('event', 'Événement'), ('announcement', 'Annonce')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('author', models.CharField(max_length=100)),
                ('author_role', models.CharField(max_length=100)),
                ('author_avatar', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('Toutes', 'Toutes'), ('Sécurité', 'Sécurité'), ('Finance', 'Finance'), ('Formation', 'Formation'), ('Production', 'Production'), ('Partenariat', 'Partenariat'), ('Environnement', 'Environnement'), ('RH', 'Ressources Humaines')], max_length=50)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='actualites.article')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualites.article')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualites.polloption')),
            ],
            options={
                'unique_together': {('article', 'user_id')},
            },
        ),
    ]
