# Generated by Django 5.2.6 on 2025-10-07 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('news', 'Actualité'), ('announcement', 'Annonce')], max_length=20)),
                ('title', models.CharField(blank=True, help_text="Titre de l'article (optionnel)", max_length=200, null=True)),
                ('content', models.TextField(blank=True, help_text="Contenu de l'article (optionnel)", null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date de publication (par défaut: maintenant)')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Heure de publication (par défaut: maintenant)')),
                ('author', models.CharField(blank=True, help_text="Auteur de l'article (optionnel)", max_length=100, null=True)),
                ('author_role', models.CharField(blank=True, help_text="Rôle de l'auteur (optionnel)", max_length=100, null=True)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('category', models.CharField(choices=[('Toutes', 'Toutes'), ('Sécurité', 'Sécurité'), ('Finance', 'Finance'), ('Formation', 'Formation'), ('Production', 'Production'), ('Partenariat', 'Partenariat'), ('Environnement', 'Environnement'), ('RH', 'Ressources Humaines')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_images', models.JSONField(blank=True, help_text='Liste des URLs des images de la galerie', null=True)),
                ('gallery_title', models.CharField(blank=True, help_text='Titre de la galerie de photos', max_length=200, null=True)),
                ('video', models.FileField(blank=True, help_text='Fichier vidéo uploadé', null=True, upload_to='videos/')),
                ('video_poster', models.ImageField(blank=True, help_text='Image de couverture pour la vidéo', null=True, upload_to='video_posters/')),
                ('content_type', models.CharField(choices=[('text_only', 'Texte seul'), ('image_only', 'Image seule'), ('text_image', 'Texte + Image'), ('gallery', 'Galerie de photos'), ('video', 'Vidéo')], default='text_only', help_text="Type de contenu pour adapter l'affichage de la carte", max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
