# Generated by Django 5.2.6 on 2025-10-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_avatar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_role',
        ),
    ]
