# Generated by Django 5.2.6 on 2025-09-08 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0004_add_video_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, help_text="Auteur de l'article (optionnel)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_role',
            field=models.CharField(blank=True, help_text="Rôle de l'auteur (optionnel)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date de publication (par défaut: maintenant)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Heure de publication (par défaut: maintenant)'),
        ),
    ]
