# Generated by Django 5.2.6 on 2025-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0005_make_date_time_author_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text="Contenu de l'article (optionnel)", null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, help_text="Titre de l'article (optionnel)", max_length=200, null=True),
        ),
    ]
