# Generated by Django 5.2.6 on 2025-11-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0005_remove_article_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, help_text="Titre de l'article (optionnel)", max_length=1000, null=True),
        ),
    ]
