# Generated by Django 5.2.6 on 2025-09-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0006_make_title_content_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollvote',
            name='option',
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='question',
        ),
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('text_only', 'Texte seul'), ('image_only', 'Image seule'), ('text_image', 'Texte + Image'), ('gallery', 'Galerie de photos'), ('video', 'Vidéo')], default='text_only', help_text="Type de contenu pour adapter l'affichage de la carte", max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('news', 'Actualité'), ('announcement', 'Annonce')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.DeleteModel(
            name='PollVote',
        ),
    ]
